insert into puesto (nombre, tipoComida, referencias, latitud, longitud)
values 	("Ensaladas & Baguettes - 1", "Rápida", "Estacionamiento", 0.0, 0.0),
		("Flautas & Chilaquiles - 2", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Pizzas & Más - 3", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Quesadillas & Tacos - 4", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Chapatas & Enchiladas - 5", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Frutas & Ensaladas - 6", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Burritos & Chilaquiles - 7", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Dulces & Refrescos - 8", "Snacks", "Estacionamiento", 0.0, 0.0),
        ("Taquitos de Guisado - 9", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Diez", "Rápida", "Estacionamiento", 0.0, 0.0),
        ("Once", "Comida corrida", "Estacionamiento", 0.0, 0.0),
        ("Puesto", "Snacks", "Atrás de la cafetería", 0.0, 0.0),
        ("Chilaquiles & Pambazos", "Rápida", "Atrás de la cafetería", 0.0, 0.0),
        ("Puesto de sushi", "Sushi / Rápida", "Atrás de la cafetería", 0.0, 0.0),
        ("Puesto", "Comidas completas", "Atrás de la cafetería", 0.0, 0.0),
        ("La Tía Aly", "Comida casera", "Atrás de la cafetería", 0.0, 0.0),
        ("Harry's", "Rápida", "Atrás de la cafetería", 0.0, 0.0),
        ("050", "Snacks", "Atrás de la cafetería", 0.0, 0.0),
        ("Frosty", "Helados / Nieves", "Atrás de la cafetería", 0.0, 0.0),
        ("Cafetería", "Por peso", "Dentro de la cafetería", 0.0, 0.0);